[graph]
all-features = false
features = ["luajit"]
exclude-dev = true

[advisories]

[bans]
multiple-versions = "allow"

# Not exhaustive, just whitelist the current dependency tree
[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "Unicode-3.0", "Zlib"]
