#!/usr/bin/env lua
package.path = (os.getenv("SILE_PATH") and os.getenv("SILE_PATH").."/?.lua" or "") .. ';/usr/lib/sile/?;/usr/local/lib/sile/?.lua;' .. package.path 
SILE = require("core/sile")
io.stdout:setvbuf 'no'
if not os.getenv 'LUA_REPL_RLWRAP' then
  print('This is SILE '..SILE.version)
end
SILE.parseArguments()
if unparsed and unparsed[1] then
  SILE.masterFileName = unparsed[1]
  SILE.readFile(unparsed[1])
else
  SILE.repl()
end
