#!/usr/bin/env lua
SILE = require("core/sile")
io.stdout:setvbuf 'no'
SILE.parseArguments()
print('This is SILE '..SILE.version)
if (arg and arg[1]) then
  SILE.readFile(arg[1])
else
  SILE.repl()
end
