SILE = require("core/sile")

describe("The measurement convertor", function()
  it("should exist", function()
    assert.is.truthy(SILE.toPoints)
  end)
  it("should work for points, units explicit", function () assert.is.equal(20, SILE.toPoints(20,"pt")) end)
  it("should work for points, units implicit", function () assert.is.equal(20, SILE.toPoints("20 pt")) end)
  it("should work for inches, units implicit", function () assert.is.equal(14.4, SILE.toPoints("0.2 in")) end)
end)
