SILE = require("core.sile")
SILE.input.backend = "dummy"
SILE.init()

describe("The frame factory", function ()
   require("classes.plain")({})

   it("should exist", function ()
      assert.is.truthy(SILE.newFrame)
   end)

   describe("Simple", function ()
      local frame = SILE.newFrame({ id = "hello", top = 20, left = 30, bottom = 200, right = 300 })
      it("should exist", function ()
         assert.is.truthy(frame)
      end)
      it("should have width", function ()
         assert.is.equal(270, frame:width():tonumber())
      end)
      it("should have height", function ()
         assert.is.equal(180, frame:height():tonumber())
      end)
      it("should be registered in the class frames table", function ()
         assert.is.truthy(SILE.frames["hello"])
         assert.is.equal(frame, SILE.frames["hello"])
      end)
   end)
end)
