SILE = require("core.sile")
SILE.input.backend = "dummy"
SILE.init()

describe("The frame factory", function ()
   require("classes.plain")({})

   it("should exist", function ()
      assert.is.truthy(SILE.newFrame)
   end)

   describe("Simple", function ()
      local frame = SILE.newFrame({ id = "hello", top = 20, left = 30, bottom = 200, right = 300 })
      it("should be a frame", function ()
         local isframe = SILE.types.frame:class_of(frame)
         assert.is.truthy(isframe)
      end)
      it("should have width", function ()
         assert.is.equal(270, frame:width():tonumber())
      end)
      it("should have height", function ()
         assert.is.equal(180, frame:height():tonumber())
      end)
      it("should be registered in the class frames table", function ()
         local hello = SILE.frames:pull("hello")
         assert.is.truthy(hello)
         assert.is.equal(frame, hello)
      end)
   end)
end)
