#!/usr/bin/perl
use strict;
use warnings;
use IPC::Run qw(run);
my ($title, $fold, @cmd) = @ARGV;
my ($out_and_err);
run \@cmd, '>&', \$out_and_err;
print "$title\n";
if ($? == 0) { print "travis_fold:start:$fold\r"; }
print $out_and_err;
if ($? == 0) { print "travis_fold:end:$fold\r"; }
exit $? >> 8;
