#!/usr/bin/env sh
set -e

: "${ARCHTAG:=}"

DESC=$(git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')

RUNTIME_DEPS='fontconfig freetype2 gentium-plus-font harfbuzz icu lua'
BUILD_DEPS='git libpng luarocks poppler zlib'

: "${DOCKER_BUILDKIT:=1}"
export DOCKER_BUILDKIT

docker build \
	--build-arg ARCHTAG="$ARCHTAG" \
	--build-arg VCS_REF="${1:-$DESC}" \
	--build-arg RUNTIME_DEPS="$RUNTIME_DEPS" \
	--build-arg BUILD_DEPS="$BUILD_DEPS" \
	--tag $DOCKER_REPO:$DOCKER_TAG \
	./
