name: Versioning

on:
  release:
    types: [ created, published, edited ]

jobs:

  actions-tagger:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update release tags
        uses: Actions-R-Us/actions-tagger@v2
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          publish_latest_tag: true
